CREATE TABLE `Questions` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Q` VARCHAR(100) NOT NULL,
    `A` VARCHAR(50) NOT NULL,
    `B` VARCHAR(50) NOT NULL,
    `C` VARCHAR(50) NOT NULL,
    `D` VARCHAR(50) NOT NULL,
    `R` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `Joueurs` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Nom` VARCHAR(20) NOT NULL,
    `Prenom` VARCHAR(20) NOT NULL,
    `Classe` VARCHAR(20) NOT NULL,
    `Score` int(4) NOT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

<--RESET DE LA TABLE -->

DROP TABLE 'Joueurs';
CREATE TABLE `Joueurs` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Nom` VARCHAR(20) NOT NULL,
    `Prenom` VARCHAR(20) NOT NULL,
    `Classe` VARCHAR(20) NOT NULL,
    `Score` int(4) NOT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;